version: '3.7'

services:
  chessapp: 
    container_name: chessapp
    build:
      context: .
      dockerfile: ${DOCKERFILE_FOR_FRONTEND}
    env_file: '.env' 
    ports:
      - ${PRODUCTION_PORT}:${INTERNAL_NGINX_PORT}
    environment:
      - CHOKIDAR_USEPOLLING=true

  backendsocket: 
    container_name: 'backendsocket'
    expose:
      - ${REACT_APP_BACKEND_PORT}
    build:
      context: .
      dockerfile: server/DockerfileForCompose
    env_file: '.env'  
    ports:
      - "${REACT_APP_BACKEND_PORT}:${REACT_APP_BACKEND_PORT}"