version: '3.7'

services:
#   postgresqldb:
#     container_name: ${DBHOST}
#     image: postgres:14.1-alpine
#     restart: always
#     environment:
#       - POSTGRES_USER=${DBUSERNAME}
#       - POSTGRES_PASSWORD=${DBPASSWORD}
#       - POSTGRES_DB=${DBDATABASE}
    # ports:
      # - "${DBPORT}:5432"
   
  chessapp: 
    container_name: chessapp
    build:
      context: .
      dockerfile: ${DOCKERFILE_FOR_FRONTEND}
    env_file: '.env' 
    ports:
      - ${PRODUCTION_PORT}:${INTERNAL_NGINX_PORT}
    environment:
      - CHOKIDAR_USEPOLLING=true

  backendsocket: 
    container_name: 'backendsocket'
    expose:
      - ${REACT_APP_BACKEND_PORT}
    build:
      context: .
      dockerfile: ${DOCKERFILE_FOR_BACKEND}
    env_file: '.env'  
    ports:
      - "${REACT_APP_BACKEND_PORT}:${REACT_APP_BACKEND_PORT}"